name: Verify dist
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  verify-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install npm dependencies
        run: npm ci --include=dev

      - name: Build and compare move dist
        run: |
          esbuild ./src/move/main.ts --bundle --outfile=./dist/move/main.new.js --platform=node --target=node20.12.0 &&
          diff -q ./dist/move/main.js ./dist/move/main.new.js

      - name: Build and compare restore dist
        run: |
          esbuild ./src/restore/main.ts --bundle --outfile=./dist/restore/main.new.js --platform=node --target=node20.12.0 &&
          diff -q ./dist/restore/main.js ./dist/restore/main.new.js

      - name: Build and compare save dist
        run: |
          esbuild ./src/save/main.ts --bundle --outfile=./dist/save/main.new.js --platform=node --target=node20.12.0 &&
          diff -q ./dist/save/main.js ./dist/save/main.new.js
